name: CI Pipeline for ML Model

# --- Trigger Conditions ---
# This workflow runs on any push to the 'main' branch
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering from the Actions tab

# --- Job Definition ---
jobs:
  build-and-test:
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    # --- Steps ---
    # A job is a sequence of steps
    steps:
      # Step 1: Check out the repository's code
      # This downloads your code (main.py, etc.) into the runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up a Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Specify the Python version

      # Step 3: Install all required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Lint code with Ruff for style and errors
      - name: Lint with Ruff
        run: ruff check .

      # --- NEW DEBUGGING STEP ---
      # We will list all files to see if the model is present and what its size is.
      - name: Debug: List files in workspace
        run: ls -la

      # Step 5: Run the unit and integration tests with Pytest
      - name: Run tests with Pytest
        run: pytest

      # Step 6: (Optional) Build a Docker image if tests pass
      # This step is commented out by default but can be enabled.
      # - name: Build Docker image
      #   run: docker build -t my-ml-api .

